### PR TITLE
DocC Base Path 

### PR DESCRIPTION
**Pull request by maxxfrazer**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Add hosting base path of `MessageKit` for DocC deployment.

Any relevant logs, error output, etc?
-------------------------------------

URL should now be "https://messagekit.github.io/MessageKit/documentation/messagekit" once deployed.

### CODE REVIEW

**Comment by maxxfrazer** [comment]
docs also deployed on SPI now:
https://swiftpackageindex.com/MessageKit/MessageKit/main/documentation/messagekit

**Review by Kaspik — APPROVED** [review]

**Comment by maxxfrazer** [comment]
Ok now I don’t know why the deploy failed, should have fetched it with package resolve. Try a re-run?
https://github.com/MessageKit/MessageKit/actions/runs/2948910456/workflow

**Comment by Kaspik** [comment]
image

image

**Comment by maxxfrazer** [comment]
Launched the same on my fork, deployment is ok:
https://maxxfrazer.github.io/MessageKit/documentation/messagekit/

**Comment by maxxfrazer** [comment]
Seems the problem could be caching 🙄 same issue as shown here:
https://forums.swift.org/t/xcode-and-swift-package-manager/44704

**Comment by Kaspik** [comment]
Yeah, wrong derived data path to be part of the project folder. Can you change?

**Comment by maxxfrazer** [comment]
Can do, sorry about all the PRs and fixes 😓

**Pull request merged**
