### PR TITLE
Increase Unit Test coverage

### PR DESCRIPTION
**Pull request by pryaniq**
Increase Unit Test coverage.

WIP on #96

### CODE REVIEW

**Comment by SD10** [comment]
@pryaniq This is awesome ❤️! I'll be able to review it in more depth later

**Comment by SD10** [comment]
@pryaniq Just wanted to follow up. I was able to get part way through reviewing this tonight. It's looking good 👍 Hope to get this merged in this week

**Comment by SD10** [comment]
@nathantannar4 We're also going to have to try and get this merged in before it becomes stale. Some of these tests involve the `MessageInputBar`.

**Comment by nathantannar4** [comment]
I'm no expert in XCTest but we def need this. I checked the tests for MessageInputBar and after my updates there will be some tests that fail. Should we really be testing things like default properties?

**Comment by SD10** [comment]
@nathantannar4 Yeah I definitely think it's reasonable to test defaults. We can catch things like "Aa" vs "New Message" 🤣 Among other things~

**Comment by SD10** [comment]
@pryaniq & @LeLuckyVint Thanks for taking the time to get the unit tests started 💯 I've invited you both to the organization 👍 No pressure if you're not feeling up to it 😎

**Review by SD10 — APPROVED** [review]

**Comment by pryaniq** [comment]
@SD10 Thank you for invitation, cheers! 🍺 
In the future I will continue working on unit tests :)

**Pull request merged**
