### PR TITLE
Remove unnecessary Avatar.playground

### PR DESCRIPTION
**Pull request by zntfdr**
~~As of https://github.com/MessageKit/MessageKit/pull/315/ the argument is now `initials`~~
See comments below

Any relevant logs, error output, etc?
-------------------------------------
Incorrect argument label in call (have 'initals:', expected 'initials:')

### CODE REVIEW

**Comment by SD10** [comment]
Typo linting skillz level 💯 😆

**Comment by zhongwuzw** [comment]
@SD10 , this file maybe can removed. I think it's useless.

**Comment by zntfdr** [comment]
@SD10 😆
@zhongwuzw I was wondering the same 🤔

**Comment by SD10** [comment]
@zntfdr Feel free to remove it. 
With our current setup it is not even visible to the ChatExample project 👍

**Comment by zntfdr** [comment]
@SD10 done :)

**Review by zhongwuzw — APPROVED** [review]

**Review by zhongwuzw — CHANGES_REQUESTED** [review]
Please remove the `Avatar.playground` reference from `Example`'s `project.pbxproj`

**Comment by zntfdr** [comment]
Woops! Will do later today 👍🏻

**Comment by zntfdr** [comment]
@zhongwuzw should be done now 💯

**Review by zhongwuzw — APPROVED** [review]

**Pull request merged**
