### PR TITLE
Only apply textColor for .text case of MessageData

### LINKED ISSUE #624: Change textColor method behavior on MessagesDisplayDelegate.
Currently, the `textColor(for:at:in)` message of `MessagesDisplayDelegate` applies to both the `.text(String)` and `.attributedText(NSAttributedString)` cases of `MessageData`.

This is a source of confusion when an`.attributedText` message's text color get's overridden by the delegate method. I think I originally set it up like this to avoid confusion but IMO this is not good behavior as it is still confusing and limits what can be done with `.attributedText`.

**TL;DR** we need to make `textColor(for:at:in)` only apply to `.text` messages.

### PR DESCRIPTION
**Pull request by cwalo**
Resolves #624

### CODE REVIEW

**Review by SD10 — COMMENTED** [review]
Needs a CHANGELOG entry under changed. Non-API breaking. Should be listed at bottom of changed section as we list API breaking changes first

**Comment by cwalo** [comment]
@SD10 updated 👍

**Comment by SD10** [comment]
@zhongwuzw if you agree with this please merge

**Review by zhongwuzw — APPROVED** [review]
💯

**Pull request merged**
