### PR TITLE
Use HTML comments to clear up the PR template

### PR DESCRIPTION
**Pull request by BasThomas**
(Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)

What does this implement/fix? Explain your changes.
---------------------------------------------------
Meta change! This converts the lines in parentheses within the Pull Request template to HTML comments, so they do not appear in the rendered Pull Request comment.

Does this close any currently open issues?
------------------------------------------
…

Any relevant logs, error output, etc?
-------------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
https://twitter.com/_SD10_/status/923434393712119808 :)

Where has this been tested?
---------------------------
**Devices/Simulators:** …

**iOS Version:** …

**Swift Version:** …

**MessageKit Version:** …

### CODE REVIEW

**Review by SD10 — APPROVED** [review]
💯 Thank you @BasThomas 😃

**Comment by SD10** [comment]
Epic fail. Looks like a status code `500` 😭 😭

**Comment by SD10** [comment]
@BasThomas Did you get an invite? It resulted in response code `500` so I resent the payload and received `200` that time. However, the response body said you're already a member 🤔

**Comment by BasThomas** [comment]
Got it 👍

**Pull request merged**
