### PR TITLE
Add overridable UIScrollView Delegate

### PR DESCRIPTION
**Pull request by mehmetbaykar**
It has scroll view delegate functions to listen to the scroll action of the message view controller. This will help developers override any action they want in one of these delegate functions.

### CODE REVIEW

**Comment by Kaspik** [comment]
I would really appreciatw screenshot and video of the behavior a d how it works. Thanks! :)

**Comment by mehmetbaykar** [comment]
Hi @Kaspik 
If someone is interested in adding new capabilities to messageCollectionView, they may need its scrolling callback. So adding scroll delegates to MessagesViewController will fix this issue.

**Comment by Kaspik** [comment]
I understand that, but this PR also adds some button and stuff so I would like to see that. :)

**Comment by mehmetbaykar** [comment]
Sorry again. The second commit should've been here as well. I will make a new PR

**Pull request closed without merging**
