### PR TITLE
Downsize logo

### PR DESCRIPTION
**Pull request by hyouuu**
The front page images are huge, so trying to downsize them. You can go to https://github.com/MessageKit/MessageKit/tree/hyouuu-patch-1 to see it

### CODE REVIEW

**Review by martinpucik — APPROVED** [review]
LGTM! 🚀 
@hyouuu did you try to center the logo too?

**Comment by alexmomotiuk** [comment]
Cool 👍🏻
Maybe we should consider an option where we leave logo on the top and move screenshot of example in separate section ?

**Comment by hyouuu** [comment]
Yes both agreed, and I'm really bad at html - would either of you like to center it and maybe move the 2nd screenshot down?

**Comment by alexmomotiuk** [comment]
Okay I will try to do it on weekends.

**Review by Kaspik — APPROVED** [review]
Please check my changes - centered, moved. :)

**Comment by Kaspik** [comment]
Btw - please point to `development` and merge development here - there will be some conflicts.

**Review by alexmomotiuk — APPROVED** [review]

**Pull request merged**
