### PR TITLE
Added ability to specify additionalBottomSpace for keyboardManager

### PR DESCRIPTION
**Pull request by Almaz5200**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Creates an open method that allows to specify withAdditionalBottomSpace argument for InputBarAccessoryView's bind method. This is necessary when MessageView does not occupy full screen and there is something on the bottom (in our case banner view)

Does this close any currently open issues?
------------------------------------------
I couldn't find any

Where has this been tested?
---------------------------
**Devices/Simulators:** iPhone 15 Pro, iPhone 15 Pro simulator

**iOS Version:** 17

**Swift Version:** 5.9

**MessageKit Version:** main branch

### CODE REVIEW

**Review by fukemy — APPROVED** [review]
look good

**Review by Kaspik — APPROVED** [review]

**Comment by vvyskocil** [comment]
It seems there is a issue with additionalBottomSpace for keyboardManager, I override the method to take reserve some space for a information banner at the top of the MessageView list, when I start typing text in the inputBar the virtual keyboard is raised and the inputBar is going up with it, this is ok. But as soon as I touch the message list to scroll it, the inputBar disappear and the bottom of the message list is under the virtual keyboard.

IMG_0685

After scrolling the message list:

IMG_0686

@Almaz5200 I'm missing something ?

**Comment by Almaz5200** [comment]
If your message is at the top I don't think you need to override that method, if I understand your case correctly. I'd try just removing this override and checking how is it going to behave afterwards, both with keyboard open and closed

**Comment by Almaz5200** [comment]
My initial motivation for this was reserving space at the bottom of the screen, bellow the inputBar

**Comment by vvyskocil** [comment]
@Almaz5200 thank you for the quick response! I removed the override, then the inputBar is always hidden by the keyboard... When the override is in place at least the inputBar is at the right place until I touch the message list.

**Comment by Almaz5200** [comment]
In that case I am not sure what could be the reason, I don't think it is related to that override. In our case we too reserve some space at the top, but it didn't require that override to accomplish

**Pull request merged**
