### PR TITLE
Fix inputTextView layout issue when rotated

### PR DESCRIPTION
**Pull request by zhongwuzw**

### CODE REVIEW

**Comment by nathantannar4** [comment]
What does the begin and end editing do

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zhongwuzw** [comment]
@nathantannar4 , it's the standard operation, see [Apple Document](https://developer.apple.com/library/content/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/CustomTextProcessing/CustomTextProcessing.html#//apple_ref/doc/uid/TP40009542-CH4-SW63)

**Comment by nathantannar4** [comment]
Good to know 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
It probably just calls notifications

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zhongwuzw** [comment]
Besides notifications, it maybe do some extra processing,like:

> invoke its own processEditing method, fixing attributes within the recorded range of changed characters. See Attribute Fixing for information about attribute fixing.

**Comment by nathantannar4** [comment]
Good to know. I wonder if applying those attributes are needed then

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zhongwuzw** [comment]
Emm, I think it's need infer from the document, maybe would not work correctly in some situations if not added `begin`、`end`.

**Review by nathantannar4 — APPROVED** [review]

**Pull request merged**
