### PR TITLE
fixing reuse bug.

### PR DESCRIPTION
**Pull request by jimijings11**
fixing reuse bug.

What does this implement/fix? Explain your changes.
---------------------------------------------------
…

Does this close any currently open issues?
------------------------------------------
…

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
**Devices/Simulators:** …

**iOS Version:** …

**Swift Version:** …

**MessageKit Version:** …

### CODE REVIEW

**Comment by nathantannar4** [comment]
Could you please elaborate on how this was a bug effecting your project? To instantiate a media image cell for MessageKit a MediaItem would be required.

**Comment by jvcdoom** [comment]
When i have more MediaMessageCell in chat and i scroll sometimes it not display proper image in that cell. So i overwrite this method and the problem gone

**Comment by jimijings11** [comment]
When i have more MediaMessageCell in chat and i scroll sometimes it not
display proper image in that cell. So i overwrite this method and the
problem gone.

wt., 19 lut 2019 o 09:10 Nathan Tannar <notifications@github.com>
napisał(a):

**Comment by SD10** [comment]
Thank you for contributing to MessageKit! I've invited you to join the MessageKit GitHub organization - no pressure to accept! If you'd like more information on what that means, check out our [contributing guidelines](https://github.com/MessageKit/MessageKit/blob/master/CONTRIBUTING.md) and join the [MessageKit Slack channel](https://join.slack.com/t/messagekit/shared_invite/enQtMjI4NzIzNzMyMzU0LTEyNmYzNzBlNjNiYjAwYjY1ZjhkMmVjNDE4OGNlMDY1OTRmNzVmMzI4MTg3OWQzZTM2NGU4NTU3ZDE5NzkwNzQ). Feel free to reach out if you have any questions! :smiley:

**Pull request merged**
