### PR TITLE
iPhone X Keyboard Issue

### PR DESCRIPTION
**Pull request by gungorbasa**

### CODE REVIEW

**Comment by gungorbasa** [comment]
@SD10 I created a fix for iPhone X keyboard issue #207 . It seems like working pretty good.

**Comment by gungorbasa** [comment]
Even though, I have committed the UIDevice Extension, for some reason compiler complains about it :/

**Comment by SD10** [comment]
@gungorbasa Thank you for the PR 👍 We do have 2 other open PRs looking to resolve this issue. I'm not sure which is the best path forward. I hope to review them sometime this week

**Comment by nathantannar4** [comment]
Thank you for your work on this. @SD10 and I looked at the different options and determined the best solution shown in #266

**Pull request closed without merging**
