### PR TITLE
Added a `didTapBackground(in:)` method to MessageCellDelegate. 👻

### PR DESCRIPTION
**Pull request by kpennacchia**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Allows apps to detect when the user has tapped on the background of a cell, rather than its content.

The use case I have in an app I am working on is to dismiss the keyboard when the user taps on an empty space of the collection view. Typically I would do this by putting a gesture recogniser on the background view of the collection view, but because the message cells go full width, the touches are intercepted, preventing that approach from working.

Does this close any currently open issues?
------------------------------------------
#400 

Any relevant logs, error output, etc?
-------------------------------------

N/A

Any other comments?
-------------------
N/A

Where has this been tested?
---------------------------
**Devices/Simulators:** iPhone 6 device and iPhone 8 simulator.

**iOS Version:** iOS 11 and iOS 12

**Swift Version:** Swift 4.2

**MessageKit Version:** 2.0.0-Beta.1 (latest commit on the development branch as of this moment).

### CODE REVIEW

**Comment by SD10** [comment]
I think this is related to #400. I haven't had time to review this PR. @MessageKit/contributors want to take a look?

**Comment by kpennacchia** [comment]
That looks to be related, yes. I didn't see that when looking through the issues. I suppose the two solutions to choose from are:

1. Introduce a new method on `MessageCellDelegate` to indicate when the user has tapped on the cell and not its content (this pull request).
2. Or change the gesture recognition so that it no longer prevents touches on empty space being forwarded to `collectionView(_:didSelectItemAt:)` as @funct7 [has done](https://github.com/MessageKit/MessageKit/issues/400#issuecomment-427661969).

I think either solution is fine, though solution 1 may be easier for users to discover and reason about any possible side effects IMO.

**Comment by Skornos** [comment]
And what if my `.custom` cell does not inherit from `MessageContentCell`? I am facing this issue right now but this tap gesture will return `nil` on the following condition:

```
    @objc
    open func handleTapGesture(_ gesture: UIGestureRecognizer) {
        ...
        let cell = cellForItem(at: indexPath) as? MessageContentCell
        ...
    }
```

**Comment by kpennacchia** [comment]
This pull request won't solve your issue.

Not to go too far off-topic, and I haven't tried using a cell that doesn't subclass `MessageContentCell ` so I'm only guessing here, but from what I can tell you'll need to setup your own gesture recogniser on your custom cell and somehow prevent the gesture recogniser on the `MessagesCollectionView` from preventing your gesture recogniser on your custom cell from receiving touch events.

If possible, you'll be better off just subclassing `MessageContentCell`.

**Comment by SD10** [comment]
Thanks for the review @Skornos, you bring up an interesting point. 

Maybe we need to move the tap gesture recognition code to `MessagesCollectionViewCell` and then override the behavior in `MessageContentCell`?

**Comment by kpennacchia** [comment]
I think that is how it used to work, but was changed to the current behaviour with https://github.com/MessageKit/MessageKit/pull/417.

**Comment by funct7** [comment]
@Skornos Have you tried [this](https://github.com/funct7/MessageKit/tree/enhancement/did_select)? I think it might be what you're looking for.

BTW, people should not be punished for not subclassing `MessageContentCell`. I'm currently using `MessageKit`, but seriously starting to wonder if this was a good choice. It's too bloated and tries to do too much by overriding too much while breaking the behavior of the parents. 

For one, `MessagesCollectionView` is based on `UICollectionView` but you can't even get the proper behavior when using a non-`MessageContentCell` `UICollectionViewCell` subclass in it. According to LSP, the `MessagesCollectionView` is **not** a subtype of `UICollectionView`. 

As long as this library keeps "adding" more to support the behavior of a "super-type" that is has broken by already adding something, it's doomed for some serious mess.

**Comment by SD10** [comment]
@funct7 Some thoughts:

> BTW, people should not be punished for not subclassing MessageContentCell. I'm currently using MessageKit, but seriously starting to wonder if this was a good choice. It's too bloated and tries to do too much by overriding too much while breaking the behavior of the parents.

I agree, I think the fact that `MessagesCollectionViewCell` doesn't have some of this logic was an oversight when we refactored the cell class hierarchy.

> For one, MessagesCollectionView is based on UICollectionView but you can't even get the proper behavior when using a non-MessageContentCell UICollectionViewCell subclass in it. According to LSP, the MessagesCollectionView is not a subtype of UICollectionView. 

Any suggestions how you would fix this?

**Comment by nathantannar4** [comment]
#773

**Comment by funct7** [comment]
@SD10 Sorry. I'm currently busy working on a service, so I haven't been able to spend ample time to read the code thoroughly. I'll try and contribute on the way and after I finish my current project.

For now, I can only say [my solution](https://github.com/funct7/MessageKit/tree/enhancement/did_select) has served my purposes quite well. I used to mix `MessagesCollectionViewCell` with a subclass of a plain `UICollectionViewCell` and it worked okay as far as I'm concerned. After all, all I did is disable the gesture recognizer when a non-`MessagesCollectionViewCell` is tapped, so that the usual `UICollectionView` can do its thing; by "its thing", I mean a cell selection being handled in the `UICollectionViewDelegate` method `collectionView(_:didSelectItemAt:)`.

As you mentioned, moving the tap gesture handling to individual cells might be even better because that means there is no big brother tap gesture recognizer on the collection view overseeing it all. The `MessagesCollectionView` having a tap gesture recognizer also interfered with simple taps on the view itself, which is another behavior I tried to implement through `touchesBegan`. It would be great to see it go.

**Comment by Skornos** [comment]
Appreciate all the ideas, I have solved the issues by subclassing `MessageContentCell ` and hiding all the unnecessary views.

**Comment by nathantannar4** [comment]
@Skornos I have a PR open at the momemt to move the tap logic to the base cell

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@kpennacchia I'll accept this, please add a CHANGELOG entry for this change. It should go in the `Added` section and it is API breaking. Please take care to follow the format of the other entries

**Comment by kpennacchia** [comment]
@SD10 Great, that's all done now.

**Review by SD10 — APPROVED** [review]

**Comment by SD10** [comment]
Thank you for contributing to MessageKit! I've invited you to join the MessageKit GitHub organization - no pressure to accept! If you'd like more information on what that means, check out our [contributing guidelines](https://github.com/MessageKit/MessageKit/blob/master/CONTRIBUTING.md) and join the [MessageKit Slack channel](https://join.slack.com/t/messagekit/shared_invite/enQtMjI4NzIzNzMyMzU0LTEyNmYzNzBlNjNiYjAwYjY1ZjhkMmVjNDE4OGNlMDY1OTRmNzVmMzI4MTg3OWQzZTM2NGU4NTU3ZDE5NzkwNzQ). Feel free to reach out if you have any questions! :smiley:

**Pull request merged**
