### PR TITLE
New avatar view

### PR DESCRIPTION
**Pull request by gungorbasa**

### CODE REVIEW

**Comment by SD10** [comment]
Ok I will help you complete this ❤️

**Comment by gungorbasa** [comment]
Thank you :)

**Comment by SD10** [comment]
@gungorbasa Mind adding the rest of the code so I can do a final cleanup?

**Comment by SD10** [comment]
@gungorbasa Thank you for your contribution 🎉 💯 I've invited you to join the **MessageKit** organization. No pressure if you're not up to it 😃

**Comment by gungorbasa** [comment]
@SD10 Thank you for doing that. I will be honored to join you guys :)

**Pull request merged**
