### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by farhanf**
added new app built using MessageKit

What does this implement/fix? Explain your changes.
---------------------------------------------------
Just edits README.md and adds a new app built using MessageKit. 

Does this close any currently open issues?
------------------------------------------
…

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
**Devices/Simulators:** …

**iOS Version:** …

**Swift Version:** …

**MessageKit Version:** …

### CODE REVIEW

**Review by zhongwuzw — APPROVED** [review]
💯

**Comment by SD10** [comment]
Thank you for contributing to MessageKit! I've invited you to join the MessageKit GitHub organization - no pressure to accept! If you'd like more information on what that means, check out our [contributing guidelines](https://github.com/MessageKit/MessageKit/blob/master/CONTRIBUTING.md) and join the [MessageKit Slack channel](https://join.slack.com/t/messagekit/shared_invite/enQtMjI4NzIzNzMyMzU0LTEyNmYzNzBlNjNiYjAwYjY1ZjhkMmVjNDE4OGNlMDY1OTRmNzVmMzI4MTg3OWQzZTM2NGU4NTU3ZDE5NzkwNzQ). Feel free to reach out if you have any questions! :smiley:

**Comment by farhanf** [comment]
Appreciate it. Will look deeper into the library. I’ve never contributed OSS before but I like what you’re doing to update it for Swift 5. 

Reading contribution guidelines, I think I’ll start by writing docs? Took me a while to figure out accessory view. 

-Farhan

**Comment by SD10** [comment]
@farhanf improving documentation is always super helpful! 🥇

**Pull request merged**
