### PR TITLE
fix top layout constraint

### LINKED ISSUE #931: messagesCollectionView top layout constraint is not correct.
- What version of MessageKit are you using?
1.0.0
- What version of iOS are you running on?
12.0.0
- What version of Swift are you running on?
4.0
- Is the issue you're experiencing reproducable in the example app?
yes.
In some cases it can be really helpful to provide a short example of your code.
If so, please wrap these code blocks in backticks, like this:

```swift
// the problem is here, the topLayoutGuide.length is 0 in viewDidLoad, the value is set after viewDidAppear.
let top = messagesCollectionView.topAnchor.constraint(equalTo: view.topAnchor, constant: topLayoutGuide.length)
```

### PR DESCRIPTION
**Pull request by wangjiejacques**
it close #931

### CODE REVIEW

**Comment by nathantannar4** [comment]
Does this allow for translucency with the navigation bar? I'm confused as to what the issue is?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@wangjiejacques This is not a bug, its to support the behavior @nathantannar4 mentioned. Seems like there is a bug in your usage of MessageKit. You may want to take a look at this [medium article explaining extended layout in iOS](https://medium.com/@wailord/extended-layout-in-ios-pre-ios-11-5eff2debf28). Hope it helps!

**Comment by wangjiejacques** [comment]
I just print `topLayoutGuide.length` in the view did load, the value is 0, and it becomes 64 in the view did appear. as the [doc](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621367-toplayoutguide) says **Query this property within your implementation of the viewDidLayoutSubviews() method.** so I don't know why you try to use the `topLayoutGuide.length` in the view did load.

@nathantannar4 @SD10 the issue is you use `topLayoutGuide.length` in viewDidLoad, sometimes this value is 0, we should use the length after `viewDidLayoutSubviews`, or maybe you want to use `topLayoutGuide.length` as 0 ?

**Comment by SD10** [comment]
@wangjiejacques Yeah, it's very possible that we want to use `0` as the constant now. It could be leftover from the previous code. We've had so much trouble with the collectionView insets that I'm very hesitant to make any changes though. Though we still have to fix #866

**Comment by wangjiejacques** [comment]
@SD10 OK, for the bottom, I think we can fix it by `let bottom = messagesCollectionView.bottomAnchor.constraint(equalTo: bottomLayoutGuide.topAnchor)`.
For the top, if you want to use it as 0, please refactor the code `let top = messagesCollectionView.topAnchor.constraint(equalTo: view.topAnchor, constant: topLayoutGuide.length)` to `let top = messagesCollectionView.topAnchor.constraint(equalTo: view.topAnchor)`. 
For me, I don't think this is a good idea to use it as 0, and it's doesn't work for me, but it's all on you.

**Comment by nathantannar4** [comment]
@wangjiejacques Can you please show the bug as to why it's not working for you? Maybe a screenshot?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wangjiejacques** [comment]
@nathantannar4 
I have a message view with only one message, when the keyboard displayed, the message is under the navigation bar.

**Comment by SD10** [comment]
> @SD10 OK, for the bottom, I think we can fix it by let bottom = messagesCollectionView.bottomAnchor.constraint(equalTo: bottomLayoutGuide.topAnchor).

We want to pin to the view not the layout guides

**Comment by nathantannar4** [comment]
@wangjiejacques  can you reproduce it in the example? If so please list the steps. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@wangjiejacques We appreciate you taking the time to submit this PR, I'm going to close due to inactivity. Let us know in your issue if the problem persists

**Comment by alobaili** [comment]
@SD10 @nathantannar4 I just tried MessageKit for the first time and faced this issue. This time I have a GIF:
ezgif-4-0c17aa2afbb4

I think the cause of this behavior is not pinning the `messagesCollectionView` to `safeAreaLayoutGuid.topAnchor`.

Here's the view hierarchy:
image

I think it's best to use `safeAreaLayoutGuid` for top and bottom constraints of the `messagesCollectionView`.

**Comment by fury21** [comment]
Problem still actual

**Comment by fukemy** [comment]
yes, confirm still actual

**Pull request closed without merging**
