### PR TITLE
verticaleBounce always true

### PR DESCRIPTION
**Pull request by ijameelkhan**
What does this implement/fix? Explain your changes.
---------------------------------------------------

To have the messageCollectionView bounce by default vertically.

…

Does this close any currently open issues?
------------------------------------------
Yes -  #351
…

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
**Devices/Simulators:** …

**iOS Version:** …

**Swift Version:** …

**MessageKit Version:** …

### CODE REVIEW

**Review by nathantannar4 — APPROVED** [review]

**Review by BasThomas — COMMENTED** [review]
What's with the extra whitespace?

**Comment by ijameelkhan** [comment]
I know its not efficient but I am used to add spaces between blocks of code.  Or in short just a bad habit - apologies.

**Review by SD10 — APPROVED** [review]
Yeah, way too much whitespace @ijameelkhan for future reference 😅 But it's my fault I don't have SwiftLint and Danger running after changing the project structure and switching to buddybuild. Anyways, thanks for the change!

**Comment by SD10** [comment]
Thank you for contributing to MessageKit! I've invited you to join the MessageKit GitHub organization - no pressure to accept! If you'd like more information on what that means, check out our [contributing guidelines](https://github.com/MessageKit/MessageKit/blob/master/CONTRIBUTING.md) and join the [MessageKit Slack channel](https://join.slack.com/t/messagekit/shared_invite/enQtMjI4NzIzNzMyMzU0LTEyNmYzNzBlNjNiYjAwYjY1ZjhkMmVjNDE4OGNlMDY1OTRmNzVmMzI4MTg3OWQzZTM2NGU4NTU3ZDE5NzkwNzQ). Feel free to reach out if you have any questions! :smiley:

**Pull request merged**
