### PR TITLE
Added new methods in `MessagesLayoutDelegate` for adjusting alignment of message top and bottom labels 

### PR DESCRIPTION
**Pull request by martinpucik**
What does this implement/fix? Explain your changes.
---------------------------------------------------
- Adds an option to use `MessagesLayoutDelegate` methods for adjusting message top/bottom label alignments without the need to subclass MessageSizeCalculators
- Chat example not used files cleanup

Does this close any currently open issues?
------------------------------------------
N/A

### CODE REVIEW

**Review by Kaspik — CHANGES_REQUESTED** [review]
I know it will be small but could you please create super small V4 Migration info section into Readme file for people that upgrade from V3?

**Comment by martinpucik** [comment]
There are no breaking changes yet in 4.0. I'd add the migration doc when there is something to migrate 😁

**Comment by Kaspik** [comment]
Well you have to add new functions when upgrading to it, they are not optional, right? 😅

**Comment by martinpucik** [comment]
There are default implementations in `MessagesLayoutDelegate` extension so clients don't have to add them 🙌

**Review by Kaspik — APPROVED** [review]

**Pull request merged**
