### PR TITLE
Move tap gesture from cell to collectionView

### PR DESCRIPTION
**Pull request by zhongwuzw**
Reduce tap gesture amount by move tap gesture from cell to collectionView.

### CODE REVIEW

**Comment by SD10** [comment]
@zhongwuzw Can you explain this a little more to me? It feels awkward moving this into `MessagesCollectionView`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
Would it help performance? Having one tap gesture rather than X. I know you can very easily translate a tap to a point and this get the cell that was tapped 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zhongwuzw** [comment]
@SD10 @nathantannar4 , two reasons for changes.

1. As @nathantannar4 says, it's for performance, we don't need to create tap gesture for each cell.
2. At the moment, we only need tap gesture on `messageContainerView` of `cell`, maybe we need tap handler on `headerView`、`FooterView`..... in the future，we must add more and more tap gesture. But by translate the tap gesture to `collectionView`, we can easily do it.

**Comment by SD10** [comment]
@zhongwuzw Can you add a CHANGELOG entry?

### Changed
- **Breaking Change** Moved the `handleTapGesture(_ gesture: UIGestureRecognizer)` method from `MessagesCollectionViewCell` to `MessagesCollectionView`.

**Pull request merged**
