### PR TITLE
Set the proper notification to invalidate layout.

### PR DESCRIPTION
**Pull request by bguidolim**
What does this implement/fix? Explain your changes.
---------------------------------------------------
This PR changes the source of the orientation notification. Before this change, the source was `UIDevice.orientationDidChangeNotification` and now is `UIApplication.didChangeStatusBarOrientationNotification`.

Does this close any currently open issues?
------------------------------------------
No.

Any other comments?
-------------------
There is no open issue for this, the problem regarding the source of the notification is the new values for `UIDeviceOrientation`, which are `faceUp` and `faceDown` starting on iOS 12.

Even without changing between portrait or landscape, the notification was being sent depending on the angle the user holds the device, causing the layout invalidation and, consequently, forcing the layout class to redraw everything again. It causes performance issues when scrolling.

Where has this been tested?
---------------------------
**Devices/Simulators:** iPhone X

**iOS Version:** iOS 12 and 13 beta.

**Swift Version:** 5

**MessageKit Version:** 3.0.0

### CODE REVIEW

**Comment by nathantannar4** [comment]
This is a great discovery!

I don't have an old device to test this on but can you add a @available if statement and leave the old implementation for pre iOS 12?

**Comment by bguidolim** [comment]
Hey! 👋 

There is no need to add `@available`, because the code doesn’t check a specific orientation and both implementations exists on iOS for a long time.

Starting on iOS 12, the notification is triggered more often with the old implementation, which is not necessary because since MessageKit only cares about `portrait` and `landscape`.

**Comment by nathantannar4** [comment]
Can you please add an entry in the change log ? 😁

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bguidolim** [comment]
@nathantannar4 Done. Not sure if a did it right and if I set the right branch to merge.

**Comment by nathantannar4** [comment]
Great entry description, can you just put it near the top of the change log under Upcoming Release? It's currently under the 3.0 section

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Review by nathantannar4 — APPROVED** [review]

**Comment by SD10** [comment]
Thank you for contributing to MessageKit! I've invited you to join the MessageKit GitHub organization - no pressure to accept! If you'd like more information on what that means, check out our [contributing guidelines](https://github.com/MessageKit/MessageKit/blob/master/CONTRIBUTING.md) and join the [MessageKit Slack channel](https://join.slack.com/t/messagekit/shared_invite/enQtMjI4NzIzNzMyMzU0LTEyNmYzNzBlNjNiYjAwYjY1ZjhkMmVjNDE4OGNlMDY1OTRmNzVmMzI4MTg3OWQzZTM2NGU4NTU3ZDE5NzkwNzQ). Feel free to reach out if you have any questions! :smiley:

**Pull request merged**
