### PR TITLE
iOS 14, XCode 12, Swift 5.3, goodbye iOS 11

### PR DESCRIPTION
**Pull request by Kaspik**
- drop iOS 11
- update to swift 5.3 for SPM
- bump to XCode 12
- make sure it works on iOS 14

### CODE REVIEW

**Review by martinpucik — APPROVED** [review]
LGTM! 🚀

**Comment by diegogarciar** [comment]
Hello, any specific reason to why support for iOS 11 was dropped?

**Comment by Kaspik** [comment]
Hey @diegogarciar ! Specific reason was described in https://github.com/MessageKit/MessageKit/issues/1466#issuecomment-694827256 :)

Is there anything specific you are looking for with iOS 11 support?

**Comment by diegogarciar** [comment]
Just the support itself haha. I decided last week to drop support for iOS 10 and now your telling me I also have drop it for iOS 11! Lot of iOS bumps for me in a release, but thanks for your point of view, I guess its time to leave those old OS in peace.

**Comment by Kaspik** [comment]
Yeah, dropping iOS 10 drops also some users and devices, but dropping iOS 11 should be okay. :)

**Pull request merged**
