### PR TITLE
Swift 4 support

### PR DESCRIPTION
**Pull request by Sepho**
Update main and example projects to Xcode 9 and swift 4 support

### CODE REVIEW

**Comment by SD10** [comment]
@Sepho Thanks for taking the initiative to start this. Looks like we have a build error

**Comment by Sepho** [comment]
Hi Steven,

Main project built fine for me, but on example project I had to change swift version from 3.2 to 4 on project build settings

**Comment by SD10** [comment]
@Sepho Thanks. I just forgot to update the Xcode version on CI

**Review by SD10 — APPROVED** [review]

**Comment by SD10** [comment]
@Sepho Thank you for your contribution 👍 💯 I've invited you to join the MessageKit organization. 
No pressure if you're not up to it 😃

**Pull request merged**
