### PR TITLE
Bugfix/detectors attributes

### PR DESCRIPTION
**Pull request by antoinelamy**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Fix ignored detectors attributes

Does this close any currently open issues?
------------------------------------------
#429

### CODE REVIEW

**Comment by SD10** [comment]
It would be nice if this could be targeted at `master` and then I can release it

**Comment by antoinelamy** [comment]
I can do that but it is stated in the Contributing Guidelines:

> Please DO NOT submit pull requests to the master branch

Didn't found a release branch either. Maybe it should be updated.

**Comment by antoinelamy** [comment]
@SD10 done

**Review by SD10 — APPROVED** [review]
Thank you @antoinelamy. Sorry for the confusion. We changed our workflow and I haven't updated CONTRIBUTING.md to reflect it

**Comment by SD10** [comment]
Thank you for contributing to MessageKit! I've invited you to join the MessageKit GitHub organization - no pressure to accept! If you'd like more information on what that means, check out our [contributing guidelines](https://github.com/MessageKit/MessageKit/blob/master/CONTRIBUTING.md) and join the [MessageKit Slack channel](https://join.slack.com/t/messagekit/shared_invite/enQtMjI4NzIzNzMyMzU0LTEyNmYzNzBlNjNiYjAwYjY1ZjhkMmVjNDE4OGNlMDY1OTRmNzVmMzI4MTg3OWQzZTM2NGU4NTU3ZDE5NzkwNzQ). Feel free to reach out if you have any questions! :smiley:

**Pull request merged**
