### PR TITLE
MessageContainerView updates

### PR DESCRIPTION
**Pull request by ghost**
MessageContainerView updates
Currently background color of the containerView is ignored, this needs to be fixed

### CODE REVIEW

**Comment by ghost** [comment]
Please ignore this pull request as it is trying to merge with master!

**Comment by SD10** [comment]
@oyalhi It's fine we can change the base branch to `0.7.0` later. I forgot to create a new branch

**Comment by ghost** [comment]
Ok, thanks.

**Review by SD10 — APPROVED** [review]
@oyalhi We'll probably end up using images instead of drawing the bubbles but thanks for giving this branch something to work with ❤️ 🎉

**Pull request merged**
