### PR TITLE
Fixes @available annotations to correctly report deprecation/obsoletion 👻

### PR DESCRIPTION
**Pull request by kinoroy**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Fixes some incorrectly used `@available` annotations which did not properly signal to the compiler and user that the method/class/variable was deprecated/obsoleted.

Namely, this PR will correctly obsolete:
- `MessageInputBar`
- `MessageInputBarDelegate`

and will deprecate
- `Sender`
- `Sender.id`
- `Sender.init(id: String, displayName: String)`

as previously intended.

The reason they were not working was that the deprecated/obsoleted version marker was using the _MessageKit_ library version, however `@available` expects a Swift language version. This change simply removes the version number as the deprecations and obsoletions do not depend on the Swift language version.

Does this close any currently open issues?
------------------------------------------
Not to my knowledge

Any relevant logs, error output, etc?
-------------------------------------

No

Any other comments?
-------------------
This PR will cause a small however *breaking change* to users who are still using in their code either
- `MessageInputBar`, or
- `MessageInputBarDelegate`

I assume this is OK since the code was there with the _intent_ to obsolete these all along, it just did not work properly.

Where has this been tested?
---------------------------
**Devices/Simulators:** … Simulator

**iOS Version:** … 13

**Swift Version:** … 5.0

**MessageKit Version:** 3.0.0

Note that this is a purely compile-time change, it has no runtime effects. Hence, it was tested to compile under the correct API usage and tested not to compile under incorrect API usage (example: using an obsoleted class). However I don't believe these is any way to actually write tests into the library to ensure a class/method/etc is deprecated or obsoleted.

### CODE REVIEW

**Review by alexmomotiuk — APPROVED** [review]

**Comment by hyouuu** [comment]
Please point to develop

**Comment by kinoroy** [comment]
@hyouuu  Done 👍

**Comment by hyouuu** [comment]
Now please resolve conflicts - thanks!

**Comment by kinoroy** [comment]
@hyouuu  Fixed! (BTW some tests are failing which are unrelated to this PR, I did see that you noted that in another PR so I'm assuming its all good)

**Comment by hyouuu** [comment]
Yes will fix the tests soon - thanks!

**Comment by SD10** [comment]
Thank you for contributing to MessageKit! I've invited you to join the MessageKit GitHub organization - no pressure to accept! If you'd like more information on what that means, check out our [contributing guidelines](https://github.com/MessageKit/MessageKit/blob/master/CONTRIBUTING.md) and join the [MessageKit Slack channel](https://join.slack.com/t/messagekit/shared_invite/enQtMjI4NzIzNzMyMzU0LTEyNmYzNzBlNjNiYjAwYjY1ZjhkMmVjNDE4OGNlMDY1OTRmNzVmMzI4MTg3OWQzZTM2NGU4NTU3ZDE5NzkwNzQ). Feel free to reach out if you have any questions! :smiley:

**Pull request merged**
