### PR TITLE
Update to Swift 5

### PR DESCRIPTION
**Pull request by nathantannar4**
Updates build config to Swift 5 and fixes some new lint warnings

### CODE REVIEW

**Comment by nathantannar4** [comment]
#1030

**Comment by Kalvin126** [comment]
How can we have this merged?

**Comment by nathantannar4** [comment]
Someone has mentioned bubbles aren't appearing. #1072 Still need to look into it. For now you can specify the Swift 5 branch. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kalvin126** [comment]
Looks like #1072 is now closed

**Comment by nickdowell** [comment]
@hyouuu please could the `3.0.0-swift5` branch be restored?

Anyone who followed the [previous instructions](https://github.com/MessageKit/MessageKit/blob/6dc34d4e0ab07be91b6dc1f1515d613d479934b9/README.md) to use that branch for Swift 5 support is now unable to `pod install` and 3.1.0 is not officially released yet 😬

**Comment by hyouuu** [comment]
Sorry for the trouble @nickdowell - restored!

**Pull request merged**
