### PR TITLE
Fix scroll to bottom instead of scroll to bottom bubble

### PR DESCRIPTION
**Pull request by zhongwuzw**
#404 

Maybe we can always `scrollRectToVisible` instead of `scrollToItem`.

### CODE REVIEW

**Review by SD10 — APPROVED** [review]

**Comment by nathantannar4** [comment]
So why does animated not work here?

**Comment by zhongwuzw** [comment]
@nathantannar4 ,not work? How do you use it, you use `scrollToBottom(animated: true)`?

**Comment by SD10** [comment]
I'll test this again after the holidays but `scrollToBottom()` is difficult to support in a variety of situations. It behaves differently depending on the `collectionView` `contentSize`. What we have now is working better than it not working at all 😕

**Comment by nathantannar4** [comment]
@zhongwuzw Ya I saw there was an animated parameter but in the Slack discussion we have been saying animated was not supported

**Pull request merged**
