### PR TITLE
[MessageLabel] Change privacy of properties and function to use allow…

### PR DESCRIPTION
**Pull request by JulienKode**
Change privacy of properties and function to use allow people to use it in their own cell custom

### CODE REVIEW

**Comment by nathantannar4** [comment]
What would be the use case for allowing modification of these properties? They are kept private to prevent unexpected behavior. Moreover, they are set this way to align with the MessagesCollectionViewLayout. So any changes here could mean vastly overriding the layout. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JulienKode** [comment]
As example if we want to create our own TextMessageCell that use the messageLabel, we need 

- messageLabelFont: to give the font to the messageLabel
- handleGesture: in the case the user touch the cell

In addition if we want to add our own Attributes in ranges we need:
- textStorage

May be I'm wrong and other possibilities are possible, I just do not know what is the things to do, if we want to use this view in customs cells

**Comment by nathantannar4** [comment]
So you don't need access to messageLabelFont. That's internal for a reason, used to increase performance. Setting it won't actually change the font. UILabel has a font property for that. 

Not sure about text storage as well. I feel like it should be kept private as if someone wants to create a custom TextCell they don't need access to the text storage. If you look at the file you can were we have made attributes have a didSet that will effect the text storage. Thinik of it this way, it users don't have access to text storage in a UILabel, why should they get access in MessageLabel?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JulienKode** [comment]
Ok I understand why we cannot do this for the text storage and the messageLabelFont
TextStorage was only if we want to add some attributes in the same,
But if we allow user to do that via regex it solve this problem 

For `handleGesture ` we cannot put it as public ?

**Comment by nathantannar4** [comment]
`handleGesture` is for internal use, so it would not serve someone who is implementing something custom very well. Should be kept the same. Thanks for the suggestions, but ultimately we have to keep a tight access control on things that when changed will lead to unexpected behaviour. Makes our job at solving issues submitted to GitHub much harder when they are ones such as, "Tapping address in message doesn't work"

**Comment by JulienKode** [comment]
Ok I understand makes sense too,
I’ll try with public properties

**Comment by SD10** [comment]
@nathantannar4 In our app, we made `handleGesture` public because we need it for detector types like mentions -- which MessageKit does not support. We should look into a better solution and also consider that StyledTextView does not have support for detectors (yet) either. Overall, I agree that limiting undefined behavior for now is a good idea

**Comment by JulienKode** [comment]
@SD10 Thanks for theses details

**Review by nathantannar4 — CHANGES_REQUESTED** [review]
Make messageLabelFont and textStorage private again, make handleGesture open

**Comment by JulienKode** [comment]
@nathantannar4 I've did it

**Comment by nathantannar4** [comment]
Looks good, maybe just add a changeling entry and then it can be merged

**Comment by JulienKode** [comment]
>Looks good, maybe just add a changeling entry and then it can be merged

@nathantannar4 ok I’ll add it 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Review by nathantannar4 — APPROVED** [review]

**Comment by JulienKode** [comment]
@nathantannar4 theses changes will be in the `2.0` or `2.1` ?

**Comment by nathantannar4** [comment]
2.0 they are non breaking

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JulienKode** [comment]
@nathantannar4 ok thanks

**Comment by SD10** [comment]
Thank you for contributing to MessageKit! I've invited you to join the MessageKit GitHub organization - no pressure to accept! If you'd like more information on what that means, check out our [contributing guidelines](https://github.com/MessageKit/MessageKit/blob/master/CONTRIBUTING.md) and join the [MessageKit Slack channel](https://join.slack.com/t/messagekit/shared_invite/enQtMjI4NzIzNzMyMzU0LTEyNmYzNzBlNjNiYjAwYjY1ZjhkMmVjNDE4OGNlMDY1OTRmNzVmMzI4MTg3OWQzZTM2NGU4NTU3ZDE5NzkwNzQ). Feel free to reach out if you have any questions! :smiley:

**Comment by SD10** [comment]
@nathantannar4 Thanks for taking lead here, I'm extremely busy. Please ping me when you decide to merge something though. Maybe I could offer some input.

IMO, new features/new changes should not be added to betas. Only bugfixes. This should've been something scheduled for a 2.1 release

**Comment by JulienKode** [comment]
Thanks @SD10 👍

**Pull request merged**
