### PR TITLE
add getting started section to README

### PR DESCRIPTION
**Pull request by TomWFox**
What does this implement/fix? Explain your changes.
---------------------------------------------------
There is no reference to the documentation in the README so these changes help to make it quick and easy for people to get started with the library and point the right places for help.

Does this close any currently open issues?
------------------------------------------
no

### CODE REVIEW

**Review by SD10 — APPROVED** [review]
@Tom-Fox1 Awesome! 💯 Thanks!!

**Comment by SD10** [comment]
Thank you for contributing to MessageKit! I've invited you to join the MessageKit GitHub organization - no pressure to accept! If you'd like more information on what that means, check out our [contributing guidelines](https://github.com/MessageKit/MessageKit/blob/master/CONTRIBUTING.md) and join the [MessageKit Slack channel](https://join.slack.com/t/messagekit/shared_invite/enQtMjI4NzIzNzMyMzU0LTEyNmYzNzBlNjNiYjAwYjY1ZjhkMmVjNDE4OGNlMDY1OTRmNzVmMzI4MTg3OWQzZTM2NGU4NTU3ZDE5NzkwNzQ). Feel free to reach out if you have any questions! :smiley:

**Comment by TomWFox** [comment]
I would be interested to join but I can't dedicate much if any time on a regular basis so it would just have to be as and when.

The other question I have is what restrictions would there be on what I could do? - I have a fair amount of experience using git/gitHub as an individual but not so much within an organisation so I would be worried about causing problems etc.

**Comment by SD10** [comment]
@Tom-Fox1 

> I would be interested to join but I can't dedicate much if any time on a regular basis so it would just have to be as and when.

You should never feel any pressure to contribute to open source! We don't require anything from you 😃 Joining the org is more to reward you for contributing to the project and making contributing next time even easier

> The other question I have is what restrictions would there be on what I could do? - I have a fair amount of experience using git/gitHub as an individual but not so much within an organisation so I would be worried about causing problems etc.

This is fine! You can always ask questions if you're unsure of something. We have a lot of restrictions in place so you really can't do anything too harmful. And if a mistake happens, don't panic, we can fix it 👍

**Pull request merged**
