### PR TITLE
FIxed slack link in CONTRIBUTING.md resolved #1395

### LINKED ISSUE #1395: CONTRIBUTING.md "You can get in touch with the MessageKit core team directly by joining our open Slack community channel" link broken
**Describe the bug**

The CONTRIBUTING.md "You can get in touch with the MessageKit core team directly by joining our open Slack community channel" link is broken.

### PR DESCRIPTION
**Pull request by artemas-radik**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Fixes the broken slack link in CONTRIBUTING.md.

Does this close any currently open issues?
------------------------------------------
Yes, closes #1395 

Any relevant logs, error output, etc?
-------------------------------------

None.

Any other comments?
-------------------
None.

Where has this been tested?
---------------------------
**Devices/Simulators:** …
N/A
**iOS Version:** …
N/A
**Swift Version:** …
N/A
**MessageKit Version:** …
N/A

### CODE REVIEW

**Review by kinoroy — APPROVED** [review]
Thank you for your contribution @ajradik ! 🤗

**Comment by kinoroy** [comment]
@ajradik ~~Do you mind just rebasing this off of `development` before merging? There's a bug with Danger failing on forked branches so we have to merge forks to dev right now. Then all checks should pass 👍~~ Scratch that, I needed to update development from master anyways, so I'll just do that in a separate PR, and update your branch.

**Comment by SD10** [comment]
Thank you for contributing to MessageKit! I've invited you to join the MessageKit GitHub organization - no pressure to accept! If you'd like more information on what that means, check out our [contributing guidelines](https://github.com/MessageKit/MessageKit/blob/master/CONTRIBUTING.md) and join the [MessageKit Slack channel](https://join.slack.com/t/messagekit/shared_invite/enQtMjI4NzIzNzMyMzU0LTEyNmYzNzBlNjNiYjAwYjY1ZjhkMmVjNDE4OGNlMDY1OTRmNzVmMzI4MTg3OWQzZTM2NGU4NTU3ZDE5NzkwNzQ). Feel free to reach out if you have any questions! :smiley:

**Comment by erwanmace** [comment]
The slack link is invalid. Can you guys repost?

**Comment by kinoroy** [comment]
@erwanmace here's an updated invite: https://join.slack.com/t/messagekit/shared_invite/zt-1nmj5q4c6-LTQJvqoGPmBdnAOOnYFrUQ

**Pull request merged**
