### PR TITLE
update Proposal: Move methods of MessageLabelDelegate to MessageCellDelegate so that selected cells can be acquired

### PR DESCRIPTION
**Pull request by hmuronaka**
Please check issue #1149 I wrote the detail.

### CODE REVIEW

**Comment by hyouuu** [comment]
`MessageCellDelegate` is already inheriting from `MessageLabelDelegate` - shouldn't you be able to directly use `MessageCellDelegate`?

**Comment by austinwright** [comment]
After some offline discussion I think this can be done in a non-breaking manner.

**Review by Kaspik — CHANGES_REQUESTED** [review]
As mentioned by Austin.

**Comment by Kaspik** [comment]
Closing for no further activity as original issue was auto-closed as well.

**Pull request closed without merging**
