### PR TITLE
(fix) restore an example file that was previously deleted

### PR DESCRIPTION
**Pull request by mredig**
used in `Documentation/MessageInputBar.md`

What does this implement/fix? Explain your changes.
---------------------------------------------------
A previous commit (d16e5f8078c14cbdc70085d06bea5d9874b19c18) deleted this file, seemingly not intentionally. Documentation continues to link to this now deleted file, so I restored it to the state prior to deletion.

Does this close any currently open issues?
------------------------------------------
…

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
**Devices/Simulators:** …

**iOS Version:** …

**Swift Version:** …

**MessageKit Version:** …

### CODE REVIEW

**Comment by mredig** [comment]
Upon further inspection, it kind of looks like another png that was added in that same commit (Assets/InputBarAccessoryViewLayout.png) was intended to replace the original file, but the markdown file wasn't updated. @nathantannar4 Can you confirm?

**Comment by Kaspik** [comment]
Yes I believe we replaced MessageInputBar with the InputBarAccessoryView and the image was supposed to be replaced. :)

**Comment by Kaspik** [comment]
Are you planning to use the replacement image?

**Comment by Kaspik** [comment]
Fixed.

**Pull request closed without merging**
