### PR TITLE
Refactoring MessageStyle to use CAShapeLayer

### PR DESCRIPTION
**Pull request by SD10**
Mainly opening this to leave comments on my own code. It's really rough and I'm not loving the API.

What I want to accomplish:
- [ ] Restrict MediaMessageTypes to not allow tails
- [ ] Use CAShapeLayer for TextMessageCells

### CODE REVIEW

**Comment by ndonald2** [comment]
@SD10 are there still plans to go this route, i.e. use CAShapeLayer instead of stretched images? If not, I've pinpointed a pretty significant performance improvement related to the way `MessageStyle` loads the bubble outline image. It's loading from disk every single time, which is completely unnecessary - the image data can safely be cached in memory. I'll probably open a PR either way but I just was curious what the future held for this.

From a qualitative standpoint, it improves scrolling performance from semi-choppy to what looks close to 60fps in our app running on an iPhone 6. I need to do some profiling around that but from my perspective it seems like a huge improvement.

**Comment by SD10** [comment]
@ndonald2 Yeah moving away from UIImage to CAShapeLayer is one of the biggest improvements we can make. I was just having some difficulty with the API surrounding this. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@ndonald2 Of course, I'm still open to all PRs meanwhile. Feel free to submit any suggestions you have

**Comment by SD10** [comment]
WIll re-evaluate in the future 😜

**Pull request closed without merging**
