### PR TITLE
Make KeyboardManager public, per issue #1785

### PR DESCRIPTION
**Pull request by zallanx**
What does this implement/fix? Explain your changes.
---------------------------------------------------
- Makes `KeyboardManager` a public class

Does this close any currently open issues?
------------------------------------------
- Closes issue #1785 

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------
👻

Where has this been tested?
---------------------------
**Devices/Simulators:**
- iOS Simulator
- iPhone 12 Pro

**iOS Version:**
- 16.6

**Swift Version:** 
- 5.3

**MessageKit Version:** 
- 4.2.0

### CODE REVIEW

**Review by Kaspik — APPROVED** [review]

**Comment by zallanx** [comment]
Hey @Kaspik, are all build tests required to pass before merging? Please let me know - thanks.

**Comment by Kaspik** [comment]
Example app should succeed, Danger not. Let's check please 🙏🏼

**Comment by Aphmau4545** [comment]
Ok

**Comment by yongfg** [comment]
Do we plan to have any update on this?

**Comment by Kaspik** [comment]
The failure is actually correct. Fixed in https://github.com/MessageKit/MessageKit/commit/439bb19a6f37b574f91955b32fc4c466e5608d5c, slo closing this.

**Pull request closed without merging**
