### PR TITLE
Input bar fixes continued

### PR DESCRIPTION
**Pull request by nathantannar4**
Found the issue with PR #380 

Before I thought it was correct to change the bottomAnchor to the window, after some digging it looks like we just needed to add an extra constraint and leave the old one.

### CODE REVIEW

**Comment by SD10** [comment]
@nathantannar4 once you're done with finals, we'll discuss how we can write tests for the `MessageInputBar` together. This should make your life easier and expose any existing flaws.

**Comment by girishghoda** [comment]
HI @nathantannar4 
I pod latest 0.12.0 version
When i open chat view first time inputbar show after some seconds hide inputbar
img_0176

I have already spent lot of time in chat app please help for this issue
Thanks

**Comment by girishghoda** [comment]
Hi @nathantannar4 
i have latest version : 0.12.0 ,But still inputbar issue occur
When i open chat view then show inputbar & after 1 or 2 second it hide automatically
img_0176
I had spent lot of time in chat functionality please help as soon as possible
Thanks

**Comment by nathantannar4** [comment]
I'm going to need more information to debug this. Is this a child view controller, any custom controllers, can you reproduce this in the example? This PR was for other things. Maybe message me on slack

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by girishghoda** [comment]
Hi,
Yes i used cosmicmind/material framework for material theme and i simply
push chat view as : self.navigationcontroller.pushview

On Dec 22, 2017 10:26 PM, "Nathan Tannar" <notifications@github.com> wrote:

I'm going to need more information to debug this. Is this a child view
controller, any custom controllers, can you reproduce this in the example?
This PR was for other things. Maybe message me on slack

Sent with GitHawk <http://githawk.com>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/MessageKit/MessageKit/pull/384#issuecomment-353636607>,
or mute the thread

**Comment by nathantannar4** [comment]
Ah I think you need to call becomeFirstResponder https://github.com/MessageKit/MessageKit/blob/master/Documentation/FAQs.md

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by girishghoda** [comment]
Hi @nathantannar4 

Here i explain my code:
First way :
-----------
Prevview :
self.navigationController?.pushViewController(chatViewController, animated: true)

Chatview:
class GrpMessageViewController: MessagesViewController
this way first time inputbar show & imediatly hide

Second way:
---------------
as per you said i tried with below code

1) class GrpMessageViewController: UIViewController
2) messagesViewController = MessagesViewController()
        addChildViewController(messagesViewController)
        self.view.addSubview(messagesViewController.view)
        messagesViewController.didMove(toParentViewController:self)
        self.becomeFirstResponder()

after this code inoutbar does't show (even first time not show)

Thanks

**Comment by girishghoda** [comment]
Hey @nathantannar4 
Its solved 
Actually problem in Material framework navigationcontroller

When i use this way 

let myNavigationController = UINavigationController(rootViewController: chatViewController)
self.present(myNavigationController, animated: true, completion: nil)
then it show properly
Thanks

**Comment by SD10** [comment]
@girishghoda Please move this discussion to a GitHub issue 👍. This PR is not the place for it

**Pull request merged**
