### PR TITLE
Fix Keyboard not dismiss on iOS9

### PR DESCRIPTION
**Pull request by zhongwuzw**
keyboardnotdismiss

### CODE REVIEW

**Comment by SD10** [comment]
Hey @zhongwuzw, sorry for the confusion. I changed the target branch to `master` since this was just an update to the example app and there are no API breaking changes. I can cherry pick the original commit if you'd like

**Comment by zhongwuzw** [comment]
@SD10 , Sorry, forgive my poor English, I cannot understand what you said. Do you mean that let me branch a new branch from `master` and make the commits?

**Comment by SD10** [comment]
@zhongwuzw No problem. You can do that or remove all commits except `b116fec`

**Comment by nathantannar4** [comment]
@SD10 should all those other commits be under this PR?

**Comment by zhongwuzw** [comment]
@SD10 @nathantannar4 , I make a new pull request about this issue.

**Pull request closed without merging**
