### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alexBotteri**
What does this implement/fix? Explain your changes.
---------------------------------------------------
added Ring4 in the projects list using MessageKit

Does this close any currently open issues?
------------------------------------------
…

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
**Devices/Simulators:** …

**iOS Version:** …

**Swift Version:** …

**MessageKit Version:** …

### CODE REVIEW

**Review by Kaspik — APPROVED** [review]

**Comment by Kaspik** [comment]
This needs to go from development branch against development branch.

**Comment by SD10** [comment]
This should be fine to just go into master directly 👍

**Review by SD10 — APPROVED** [review]

**Comment by Kaspik** [comment]
@SD10 The problem is that Danger has bug and is not working from forks - so we wanted to restrict that no fork goes to master...

**Comment by kinoroy** [comment]
Going to merge to dev due to the Danger issue.

**Comment by SD10** [comment]
Thank you for contributing to MessageKit! I've invited you to join the MessageKit GitHub organization - no pressure to accept! If you'd like more information on what that means, check out our [contributing guidelines](https://github.com/MessageKit/MessageKit/blob/master/CONTRIBUTING.md) and join the [MessageKit Slack channel](https://join.slack.com/t/messagekit/shared_invite/enQtMjI4NzIzNzMyMzU0LTEyNmYzNzBlNjNiYjAwYjY1ZjhkMmVjNDE4OGNlMDY1OTRmNzVmMzI4MTg3OWQzZTM2NGU4NTU3ZDE5NzkwNzQ). Feel free to reach out if you have any questions! :smiley:

**Pull request merged**
