### PR TITLE
Fix UITextView content size ambiguous issue

### PR DESCRIPTION
**Pull request by zhongwuzw**

### CODE REVIEW

**Comment by zhongwuzw** [comment]
layout_issues

**Review by nathantannar4 — APPROVED** [review]
Looks like this is a better solution and it renders the correct result

**Review by SD10 — DISMISSED** [review]
👍

**Review by nathantannar4 — CHANGES_REQUESTED** [review]
We will also need to change the update constraint method from 

```
placeholderLabelConstraintSet?.width?.constant = -(placeholderLabelInsets.left + placeholderLabelInsets.right)
```

to

```
placeholderLabelConstraintSet?.right?.constant = -placeholderLabelInsets.right
```

**Comment by SD10** [comment]
@nathantannar4 I was going to ask if you didn't want to change your mind this time 🤣 

That new label is too similar to the colors of existing labels 🤔 

I also think labels on PRs are stupid. I never remember to add/remove them myself. I just created `under review` to let people know I saw their PR && `in progress` to get people off my back 😃

**Comment by zhongwuzw** [comment]
@nathantannar4 , I updated the changes.

**Review by nathantannar4 — DISMISSED** [review]

**Comment by nathantannar4** [comment]
🔥

**Comment by nathantannar4** [comment]
@zhongwuzw Can you just make a change log entry for this in the CHANGELOG.md ? These are non-breaking changes but we need to document them

**Comment by zhongwuzw** [comment]
@nathantannar4 , I added the CHANGELOG entries. Forgive my little poor English .:cn::cn:

**Review by nathantannar4 — APPROVED** [review]

**Pull request merged**
