### PR TITLE
Fix for #19

### PR DESCRIPTION
**Pull request by lzyraining**
screen shot 2017-07-31 at 11 23 09 pm

Fixing the overlapping when change device orientation.

### CODE REVIEW

**Comment by SD10** [comment]
@lzyraining what device are you using?

**Comment by lzyraining** [comment]
@SD10 iPhone 7 plus simulator

**Comment by SD10** [comment]
@lzyraining Good catch. Can this be done in `viewWillTransition(to:coordinator:)`? 
Possibly without reloading the collection view as well?

**Comment by lzyraining** [comment]
@SD10 The collection view reload is not necessary. Thanks for pointing to that. I have removed it. The key point is to invalidate the collectionLayout before subviews is layout.

Using `viewWillTransition(to:coordinator:)` seems to cause two troubles to me. I need to call `coordinator.animate(alongsideTransition: , completion: )`. It looks like during the transition it can not detect that bounds has been changed. I need to force call `messageLayout.invalidateLayout()`(Maybe I did something wrong). Another thing is that I can not control the animation.

**Comment by SD10** [comment]
@lzyraining I think I've solved this in the `MessagesCollectionViewLayout` itself by adding an invalidation context. I'd really rather leave all invalidation logic to the flow layout itself. I'll push some changes to `v0.2.0` later tonight and it would be great if you could see if this fixes the problem.

**Comment by SD10** [comment]
@lzyraining Does this layout bug still occur for you on the latest `v0.2.0`?

**Comment by lzyraining** [comment]
@SD10 Layout looks good now. But avatar is wrong placed sometimes when scroll the table.
screen shot 2017-08-01 at 3 20 56 pm

**Comment by SD10** [comment]
@lzyraining This is hard for me to reproduce. I think it's more likely to be a separate issue.

**Pull request closed without merging**
