### PR TITLE
Update Swift version in podspec

### PR DESCRIPTION
**Pull request by larryonoff**

### CODE REVIEW

**Comment by SD10** [comment]
@larryonoff Looks like CI is failing for this 🤔

**Comment by larryonoff** [comment]
@SD10 CocoaPods needs to be updated to version 1.4.0 and higher. Do you know how to do it?

**Comment by nathantannar4** [comment]
@larryonoff what is the benefit of changing the pod spec in this way?

**Comment by larryonoff** [comment]
@nathantannar4 this's needed when library supports concrete Swift version, so that CocoaPods set correct version in Pods Xcode project.

**Comment by nathantannar4** [comment]
@larryonoff wanna update for Swift 4.2 and target Branch `development`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by larryonoff** [comment]
@nathantannar4 updated target branch to `development`

**Comment by SD10** [comment]
Looks like `development` is going to be a Swift 4.2 release though 🤔

**Comment by larryonoff** [comment]
@SD10 there can be support for all swift 4.* versions. In this case this PR can be abandoned.

**Comment by nathantannar4** [comment]
@larryonoff So should this be abandoned ?

**Comment by larryonoff** [comment]
@nathantannar4 Of course It can be abandoned. But why you asking about abandoning?

**Comment by nathantannar4** [comment]
I was confused by your previous comment where you said If so it can be abandoned. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by larryonoff** [comment]
@nathantannar4 I see. I mentioned that it can be abandoned in case of MessageKit wants to support several Swift versions, e.g. 4.1 / 4.2.

I also want to note that `.swift-version` isn't used in the latest CocoaPods, but `swift_version` from `podspec`

**Comment by SD10** [comment]
Closing this. Sorry for the poor feedback @larryonoff. Appreciate you trying to help ❤️

**Pull request closed without merging**
